"PR #\(.number): \(.title)"
+ "\nURL: \(.url)"
+ "\nState: \(.state // "UNKNOWN")\(if .isDraft then " (draft)" else "" end)"
+ "\nReview decision: \(.reviewDecision // "(none)")"
+ "\nLabels: \(.labels // [] | map(.name) | join(", ") | if . == "" then "(none)" else . end)"
+ "\n\nBody:\n\(.body // "(no body)")"
+ "\n\nCommits:\n\(.commits // [] | if length == 0 then "(no commits)" else map("- " + (.messageHeadline // "(no message)")) | join("\n") end)"
+ "\n\nComments:\n\(.comments // [] | if length == 0 then "(no comments)" else map("@\(.author.login // "ghost"): \(.body // "(no body)")") | join("\n\n---\n\n") end)"
+ "\n\nReviews:\n\(.reviews // [] | if length == 0 then "(no reviews)" else map("@\(.author.login // "ghost") [\(.state // "PENDING")]: \(.body // "(no body)")") | join("\n\n---\n\n") end)"
