"Issue #\(.number): \(.title)"
+ "\nURL: \(.url)"
+ "\nState: \(.state // "UNKNOWN")"
+ "\nLabels: \(.labels // [] | map(.name) | join(", ") | if . == "" then "(none)" else . end)"
+ "\n\nBody:\n\(.body // "(no body)")"
+ "\n\nComments:\n\(.comments // [] | if length == 0 then "(no comments)" else map("@\(.author.login // "ghost"): \(.body // "(no body)")") | join("\n\n---\n\n") end)"
